language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
addons:
  apt:
    packages:
    - imagemagick
    - tcl8.5
    - tk8.5
    - libcairo2
    - libavcodec-extra
    - libavdevice-dev
    - libavfilter-dev
    - libavformat-dev
    - libavutil-dev
    - libswscale-dev
    - xvfb
    - xauth
script:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("SensorFeatureTracking")); include(joinpath("docs", "make.jl"))'
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd());
after_success:
  - julia -e 'cd(Pkg.dir("SensorFeatureTracking")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

